import { MenuItem, MenuCategory, MenuType } from './types';

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  // --- ENTRANTES ---
  { id: 'e1', name: 'Tomate Rosa', description: 'Ensalada de tomate rosa con cebolla dulce y burrata de bufala.', price: 16.00, category: MenuCategory.STARTERS, type: MenuType.FOOD, available: true, allergens: ['Lácteos'], pairingNote: 'Pide un vino blanco fresco o un rosado joven.' },
  { id: 'e2', name: 'Cecina de León', description: 'Cecina de vaca de León IGP.', price: 18.00, category: MenuCategory.STARTERS, type: MenuType.FOOD, available: true, pairingNote: 'Combina bien con tintos jóvenes o de media crianza.' },
  { id: 'e3', name: 'Jamón Ibérico de Bellota', description: 'Jamón 100% ibérico de bellota.', price: 29.00, category: MenuCategory.STARTERS, type: MenuType.FOOD, available: true, pairingNote: 'Excelente con Fino, Manzanilla o un buen Champagne.' },
  { id: 'e4', name: 'Papada Ibérica', description: 'Papada adobada 100% ibérica de bellota de Extremadura.', price: 11.00, category: MenuCategory.STARTERS, type: MenuType.FOOD, available: true },
  { id: 'e5', name: 'Pimiento-Ventresca', description: 'Ensalada de pimientos de piquillo con ventresca de atún salteada con cebolla dulce.', price: 15.00, category: MenuCategory.STARTERS, type: MenuType.FOOD, available: true, allergens: ['Pescado'] },
  { id: 'e6', name: 'Ostra Rugosa', description: 'Precio por unidad. Ostra fresca.', price: 3.00, category: MenuCategory.STARTERS, type: MenuType.FOOD, available: true, allergens: ['Moluscos'], pairingNote: 'Imprescindible maridar con Cava, Champagne o Albariño.' },
  { id: 'e7', name: 'Anchoas de Santoña', description: 'Anchoas grandes de Santoña en AOVE.', price: 18.00, category: MenuCategory.STARTERS, type: MenuType.FOOD, available: true, allergens: ['Pescado'] },
  { id: 'e8', name: 'Bloc de Foie', description: 'Servido con tostadas de pan con pasas y mermelada de arándanos.', price: 19.00, category: MenuCategory.STARTERS, type: MenuType.FOOD, available: true, allergens: ['Gluten'], pairingNote: 'Un clásico: marídalo con un blanco dulce.' },
  { id: 'e9', name: 'Surtido de Quesos', description: 'Selección de diversos quesos acompañados con frutos secos.', price: 20.00, category: MenuCategory.STARTERS, type: MenuType.FOOD, available: true, allergens: ['Lácteos', 'Frutos secos'] },
  { id: 'e10', name: 'Steak Tartar', description: 'Steak tartar de vaca madurada con aliñado casero y yema de huevo.', price: 22.00, category: MenuCategory.STARTERS, type: MenuType.FOOD, available: true, allergens: ['Huevo'] },
  { id: 'e11', name: 'Ostra a la Brasa', description: 'Ostra Rugosa pasada por la brasa.', price: 3.00, category: MenuCategory.STARTERS, type: MenuType.FOOD, available: true, allergens: ['Moluscos'] },
  { id: 'e12', name: 'Caracoles a la Brasa', description: 'Caracoles a la brasa tradicionales con Ali-oli.', price: 16.00, category: MenuCategory.STARTERS, type: MenuType.FOOD, available: true, allergens: ['Huevo'] },
  { id: 'e13', name: 'Boletus Edulis', description: 'Boletus Edulis a la brasa con yema de huevo.', price: 21.00, category: MenuCategory.STARTERS, type: MenuType.FOOD, available: true, allergens: ['Huevo'] },
  { id: 'e14', name: 'Gamba Blanca de Huelva', description: 'Gamba blanca de Huelva a la brasa (12 un.).', price: 18.00, category: MenuCategory.STARTERS, type: MenuType.FOOD, available: true, allergens: ['Crustáceos'] },
  { id: 'e15', name: 'Panceta a baja tª', description: 'Panceta hecha a baja temperatura durante 24 horas y posteriormente pasada por la brasa.', price: 16.00, category: MenuCategory.STARTERS, type: MenuType.FOOD, available: true },
  { id: 'e16', name: 'Huevos Rotos', description: 'Huevos fritos con patatas fritas y jamón ibérico de bellota.', price: 16.00, category: MenuCategory.STARTERS, type: MenuType.FOOD, available: true, allergens: ['Huevo'] },
  { id: 'e17', name: 'Pulpo a la Brasa', description: 'Pulpo a la brasa sobre una capa de patatas cocidas con AOVE y pimentón dulce.', price: 22.00, category: MenuCategory.STARTERS, type: MenuType.FOOD, available: true, allergens: ['Moluscos'] },
  { id: 'e18', name: 'Zamburiñas', description: '6 zamburiñas (Vieira del Pacífico) a la brasa ligeramente ahumadas.', price: 18.00, category: MenuCategory.STARTERS, type: MenuType.FOOD, available: true, allergens: ['Moluscos'] },

  // --- PRINCIPALES ---
  { id: 'm1', name: 'Pluma Ibérica', description: 'Corte jugoso de cerdo ibérico a la brasa.', price: 21.00, category: MenuCategory.MAINS, type: MenuType.FOOD, available: true, pairingNote: 'Un Rioja Crianza es su mejor aliado.' },
  { id: 'm2', name: 'Chuletón de Vaca Madurada', description: 'Precio por Kg (69€/kg). A la brasa.', price: 69.00, category: MenuCategory.MAINS, type: MenuType.FOOD, available: true, pairingNote: 'Obligatorio un tinto potente: Ribera del Duero o Toro.' },
  { id: 'm3', name: 'Presa Ibérica', description: 'Corte noble de cerdo ibérico.', price: 59.00, category: MenuCategory.MAINS, type: MenuType.FOOD, available: true },
  { id: 'm4', name: 'Besugo al Orio', description: 'Precio por Kg (85€/kg). Pescado salvaje a la brasa.', price: 85.00, category: MenuCategory.MAINS, type: MenuType.FOOD, available: true, allergens: ['Pescado'] },
  { id: 'm5', name: 'Longaniza de Graus', description: 'Tradicional longaniza de Graus a la brasa.', price: 13.00, category: MenuCategory.MAINS, type: MenuType.FOOD, available: true },

  // --- POSTRES ---
  { id: 'd1', name: 'Tarta de Queso', description: 'Casera y cremosa.', price: 7.00, category: MenuCategory.DESSERTS, type: MenuType.FOOD, available: true, allergens: ['Lácteos', 'Huevo', 'Gluten'] },
  { id: 'd2', name: 'Tarta al Whisky', description: 'Clásica tarta helada al whisky.', price: 6.00, category: MenuCategory.DESSERTS, type: MenuType.FOOD, available: true, allergens: ['Lácteos', 'Gluten'] },
  { id: 'd3', name: 'Tarta Sacher', description: 'Bizcocho de chocolate con mermelada.', price: 6.00, category: MenuCategory.DESSERTS, type: MenuType.FOOD, available: true, allergens: ['Gluten', 'Huevo'] },
  { id: 'd4', name: 'Coulant de Chocolate', description: 'Volcán de chocolate caliente.', price: 6.00, category: MenuCategory.DESSERTS, type: MenuType.FOOD, available: true, allergens: ['Gluten', 'Huevo', 'Lácteos'] },
  { id: 'd5', name: 'Cuajada Casera', description: 'Elaboración tradicional.', price: 5.00, category: MenuCategory.DESSERTS, type: MenuType.FOOD, available: true, allergens: ['Lácteos'] },
  { id: 'd6', name: 'Crema Catalana Casera', description: 'Con azúcar quemado crujiente.', price: 5.00, category: MenuCategory.DESSERTS, type: MenuType.FOOD, available: true, allergens: ['Lácteos', 'Huevo'] },
  { id: 'd7', name: 'Pastel Ruso de Ascaso', description: 'Especialidad de Huesca.', price: 5.00, category: MenuCategory.DESSERTS, type: MenuType.FOOD, available: true, allergens: ['Frutos secos', 'Huevo', 'Lácteos'] },
  { id: 'd8', name: 'Soufflé Black&White', description: 'Combinación de chocolates.', price: 7.00, category: MenuCategory.DESSERTS, type: MenuType.FOOD, available: true, allergens: ['Lácteos', 'Huevo'] },

  // --- VINOS TINTOS ---
  { id: 't1', name: '12 Lunas Garnacha', description: 'Somontano, joven.', price: 19, category: MenuCategory.REDS, type: MenuType.WINE, available: true },
  { id: 't2', name: 'Izadi Crianza', description: 'Rioja, 14 meses barrica, Tempranillo.', price: 20, category: MenuCategory.REDS, type: MenuType.WINE, available: true },
  { id: 't3', name: 'Viña Real Crianza', description: 'Rioja, 13-14 meses barrica, Tempranillo.', price: 20, category: MenuCategory.REDS, type: MenuType.WINE, available: true },
  { id: 't4', name: 'Ijalba Cuvée', description: 'Rioja, 10 meses barrica, Tempranillo, Graciano, Maturana.', price: 20, category: MenuCategory.REDS, type: MenuType.WINE, available: true },
  { id: 't5', name: 'U de Usarralde', description: 'Rioja, 13 meses barrica, Garnacha.', price: 21, category: MenuCategory.REDS, type: MenuType.WINE, available: true },
  { id: 't6', name: 'Valdériz de Chiripa', description: 'Ribera del Duero, 12 meses, Tempranillo, Albillo.', price: 20, category: MenuCategory.REDS, type: MenuType.WINE, available: true },
  { id: 't7', name: 'Pruno', description: 'Ribera del Duero, 12 meses, Tempranillo.', price: 21, category: MenuCategory.REDS, type: MenuType.WINE, available: true },
  { id: 't8', name: 'Lanica Quasivita', description: 'Monegros, 12 meses barrica, Marselan-Syrah.', price: 24, category: MenuCategory.REDS, type: MenuType.WINE, available: true },
  { id: 't9', name: 'Berdá Parraleta', description: 'Somontano, 6 meses barrica.', price: 22, category: MenuCategory.REDS, type: MenuType.WINE, available: true },
  { id: 't10', name: 'Sommos Merlot', description: 'Somontano, 12 meses barrica.', price: 24, category: MenuCategory.REDS, type: MenuType.WINE, available: true },
  { id: 't11', name: 'Bestué Finca Rableros', description: 'Somontano, 9 meses barrica, Tempranillo, Cabernet.', price: 19, category: MenuCategory.REDS, type: MenuType.WINE, available: true },
  { id: 't12', name: 'Sommos Crianza', description: 'Somontano, 6 meses barrica, Cab. Sauv, Syrah, Merlot.', price: 19, category: MenuCategory.REDS, type: MenuType.WINE, available: true },
  { id: 't13', name: 'Ijalba Graciano', description: 'Rioja, 10 meses barrica, Graciano.', price: 24, category: MenuCategory.REDS, type: MenuType.WINE, available: true },
  { id: 't14', name: 'Viña Real Reserva', description: 'Rioja, 22 meses barrica, Tempranillo.', price: 25, category: MenuCategory.REDS, type: MenuType.WINE, available: true },
  { id: 't15', name: 'Sommos Reserva', description: 'Somontano, 12 meses barrica, Cab. Sauv-Merlot-Tempranillo.', price: 25, category: MenuCategory.REDS, type: MenuType.WINE, available: true },
  { id: 't16', name: 'Vetus', description: 'Toro, 12 meses barrica, Tinta de Toro.', price: 25, category: MenuCategory.REDS, type: MenuType.WINE, available: true },
  { id: 't17', name: 'Conde de San Cristóbal', description: 'Ribera del Duero, 12-14 meses barrica, Tinto Fino.', price: 26, category: MenuCategory.REDS, type: MenuType.WINE, available: true },
  { id: 't18', name: 'Valdériz', description: 'Ribera del Duero, 20 meses barrica, Tinta fina.', price: 27, category: MenuCategory.REDS, type: MenuType.WINE, available: true },
  { id: 't19', name: 'Sers GR18', description: 'Somontano, 18 meses barrica, Cabernet Sauvignon-Merlot.', price: 27, category: MenuCategory.REDS, type: MenuType.WINE, available: true },
  { id: 't20', name: 'Lajas', description: 'Calatayud, 12 meses barrica, Garnacha.', price: 28, category: MenuCategory.REDS, type: MenuType.WINE, available: true },
  { id: 't21', name: 'Viñedo Saturno', description: 'Bierzo, 5 meses barrica, Mencía.', price: 28, category: MenuCategory.REDS, type: MenuType.WINE, available: true },
  { id: 't22', name: 'Veratón', description: 'Campo de Borja, 16 meses barrica, Garnacha.', price: 29, category: MenuCategory.REDS, type: MenuType.WINE, available: true },
  { id: 't23', name: 'Marqués de Vargas Reserva', description: 'Rioja, 22 meses barrica, Tempranillo-Garnacha.', price: 29, category: MenuCategory.REDS, type: MenuType.WINE, available: true },
  { id: 't24', name: 'Obergo Antiqua', description: 'Somontano, 12 meses barrica, Garnacha.', price: 31, category: MenuCategory.REDS, type: MenuType.WINE, available: true },
  { id: 't25', name: 'Enate Syrah-Shiraz', description: 'Somontano, 13 meses barrica.', price: 32, category: MenuCategory.REDS, type: MenuType.WINE, available: true },
  { id: 't26', name: 'Enate Cabernet-Cabernet', description: 'Somontano, 13 meses barrica.', price: 32, category: MenuCategory.REDS, type: MenuType.WINE, available: true },
  { id: 't27', name: 'El Sequé', description: 'Alicante, 12 meses barrica, Monastrell.', price: 32, category: MenuCategory.REDS, type: MenuType.WINE, available: true },
  { id: 't28', name: 'Familia Comenge', description: 'Ribera del Duero, 24-27 meses barrica, Tempranillo.', price: 32, category: MenuCategory.REDS, type: MenuType.WINE, available: true },
  { id: 't29', name: 'Fincas de Ganuza', description: 'Rioja, 24 meses barrica, Tempranillo, Mazuelo.', price: 35, category: MenuCategory.REDS, type: MenuType.WINE, available: true },
  { id: 't30', name: 'Bosque de Matasnos', description: 'Ribera del Duero, 12 meses barrica, Tempranillo-Merlot.', price: 38, category: MenuCategory.REDS, type: MenuType.WINE, available: true },
  { id: 't31', name: 'Juegabolos', description: 'Ribera del Duero, 28 meses barrica, Tinta del País.', price: 38, category: MenuCategory.REDS, type: MenuType.WINE, available: true },
  { id: 't32', name: 'Dominio de Atauta', description: 'Ribera del Duero, 19 meses barrica, Tinto Fino.', price: 39, category: MenuCategory.REDS, type: MenuType.WINE, available: true },
  { id: 't33', name: 'Grillo', description: 'Somontano, 13 meses barrica, Syrah-Cabernet-Garnacha.', price: 40, category: MenuCategory.REDS, type: MenuType.WINE, available: true },
  { id: 't34', name: 'Pago de Carraovejas', description: 'Ribera del Duero, 12 meses barrica, Tempranillo-Merlot.', price: 46, category: MenuCategory.REDS, type: MenuType.WINE, available: true },
  { id: 't35', name: '200 Monges Reserva', description: 'Rioja, 20 meses barrica, Tempranillo-Graciano.', price: 54, category: MenuCategory.REDS, type: MenuType.WINE, available: true },
  { id: 't36', name: 'Milsetentayseis', description: 'Ribera del Duero, 20 meses barrica, Tempranillo.', price: 58, category: MenuCategory.REDS, type: MenuType.WINE, available: true },

  // --- VINOS ROSADOS ---
  { id: 'r1', name: '12 Lunas Syrah', description: 'Somontano, joven, Syrah.', price: 19, category: MenuCategory.ROSES, type: MenuType.WINE, available: true },
  { id: 'r2', name: 'Bestué Calabeso', description: 'Somontano, joven, Garnacha.', price: 20, category: MenuCategory.ROSES, type: MenuType.WINE, available: true },

  // --- VINOS BLANCOS ---
  { id: 'w1', name: 'Naia', description: 'Rueda, 4 meses sobre lías, Verdejo.', price: 19, category: MenuCategory.WHITES, type: MenuType.WINE, available: true },
  { id: 'w2', name: 'Obergo Gëwurztraminer', description: 'Somontano, joven.', price: 19, category: MenuCategory.WHITES, type: MenuType.WINE, available: true },
  { id: 'w3', name: 'Enate 234', description: 'Somontano, joven, Chardonnay.', price: 19.5, category: MenuCategory.WHITES, type: MenuType.WINE, available: true },
  { id: 'w4', name: 'Pazo San Mauro', description: 'Rias Baixas, joven, Albariño.', price: 25, category: MenuCategory.WHITES, type: MenuType.WINE, available: true },
  { id: 'w5', name: 'Lalume', description: 'Ribeiro, sobre lías, Treixadura, Albariño, Godello.', price: 28, category: MenuCategory.WHITES, type: MenuType.WINE, available: true },
  { id: 'w6', name: 'Ijalba Blanco Crianza', description: 'Rioja, 8 meses barrica, Viura, Maturana.', price: 27, category: MenuCategory.WHITES, type: MenuType.WINE, available: true },
  { id: 'w7', name: 'Valdesil', description: 'Valdeorras, sobre lías, Godello.', price: 28, category: MenuCategory.WHITES, type: MenuType.WINE, available: true },
  { id: 'w8', name: 'Viñedo Barreiros', description: 'Bierzo, 8 meses barrica, Godello.', price: 28, category: MenuCategory.WHITES, type: MenuType.WINE, available: true },
  { id: 'w9', name: 'Manuel Rojo Colleiteiro', description: 'Ribeiro, joven, Treixadura, Lado, Godello.', price: 30, category: MenuCategory.WHITES, type: MenuType.WINE, available: true },

  // --- ESPUMOSOS ---
  { id: 's1', name: 'Torelló Brut Reserva', description: 'Corpinnat, Macabeo-Xarel.lo-Parellada.', price: 22, category: MenuCategory.SPARKLING, type: MenuType.WINE, available: true },
  { id: 's2', name: 'Llopart Brut Nature Reserva', description: 'Corpinnat, Macabeo-Xarel.lo-Parellada.', price: 25, category: MenuCategory.SPARKLING, type: MenuType.WINE, available: true },
  { id: 's3', name: 'Nicolas Feuillatte Brut Réserve', description: 'Champagne, Pinot Noir-Meunier-Chardonnay.', price: 37, category: MenuCategory.SPARKLING, type: MenuType.WINE, available: true },
  { id: 's4', name: 'Charles Heidsieck Brut Réserve', description: 'Champagne, Pinot Noir-Meunier-Chardonnay.', price: 52, category: MenuCategory.SPARKLING, type: MenuType.WINE, available: true },
  { id: 's5', name: 'Bollinger Special Cuvée', description: 'Champagne, Pinot Noir-Meunier-Chardonnay.', price: 69, category: MenuCategory.SPARKLING, type: MenuType.WINE, available: true },
];